"""Initial migration

Revision ID: 35f3ca1d2962
Revises: 
Create Date: 2023-11-16 12:31:10.567573

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '35f3ca1d2962'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # Drop foreign key constraint
    op.drop_constraint('Appointments_ibfk_1', 'Appointments', type_='foreignkey')

    # Drop tables
    op.drop_table('Clients')
    op.drop_table('Activities')
    op.drop_table('Alerts')
    op.drop_table('Users')
    op.drop_table('Appointments')
    op.drop_table('Collaborations')
    op.drop_table('DataExtraction')

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('DataExtraction',
    sa.Column('ExtractionID', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('UserID', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('Data', mysql.TEXT(), nullable=True),
    sa.Column('Timestamp', mysql.TIMESTAMP(), nullable=True),
    sa.ForeignKeyConstraint(['UserID'], ['Users.UserID'], name='DataExtraction_ibfk_1'),
    sa.PrimaryKeyConstraint('ExtractionID'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('Collaborations',
    sa.Column('CollaborationID', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('SenderID', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('ReceiverID', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('Message', mysql.TEXT(), nullable=True),
    sa.Column('Document', sa.BLOB(), nullable=True),
    sa.Column('Timestamp', mysql.TIMESTAMP(), nullable=True),
    sa.ForeignKeyConstraint(['ReceiverID'], ['Users.UserID'], name='Collaborations_ibfk_2'),
    sa.ForeignKeyConstraint(['SenderID'], ['Users.UserID'], name='Collaborations_ibfk_1'),
    sa.PrimaryKeyConstraint('CollaborationID'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('Appointments',
    sa.Column('AppointmentID', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('ClientID', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('Date', mysql.DATETIME(), nullable=True),
    sa.Column('Purpose', mysql.TEXT(), nullable=True),
    sa.ForeignKeyConstraint(['ClientID'], ['Clients.ClientID'], name='Appointments_ibfk_1'),
    sa.PrimaryKeyConstraint('AppointmentID'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('Users',
    sa.Column('UserID', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('UserType', mysql.VARCHAR(length=20), nullable=False),
    sa.Column('Username', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('Password', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('Email', mysql.VARCHAR(length=50), nullable=False),
    sa.PrimaryKeyConstraint('UserID'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('Alerts',
    sa.Column('AlertID', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('UserID', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('AlertType', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('Deadline', mysql.DATETIME(), nullable=True),
    sa.Column('Action', mysql.TEXT(), nullable=True),
    sa.ForeignKeyConstraint(['UserID'], ['Users.UserID'], name='Alerts_ibfk_1'),
    sa.PrimaryKeyConstraint('AlertID'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('Activities',
    sa.Column('ActivityID', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('UserID', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('ClientID', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('ActionType', mysql.VARCHAR(length=20), nullable=True),
    sa.Column('Timestamp', mysql.TIMESTAMP(), nullable=True),
    sa.ForeignKeyConstraint(['ClientID'], ['Clients.ClientID'], name='Activities_ibfk_2'),
    sa.ForeignKeyConstraint(['UserID'], ['Users.UserID'], name='Activities_ibfk_1'),
    sa.PrimaryKeyConstraint('ActivityID'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('Clients',
    sa.Column('ClientID', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('UserID', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('ClientStatus', mysql.VARCHAR(length=20), nullable=True),
    sa.ForeignKeyConstraint(['UserID'], ['Users.UserID'], name='Clients_ibfk_1'),
    sa.PrimaryKeyConstraint('ClientID'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
